/*
 * File: app/view/LoginFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vertex.view.LoginFormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.LoginFormPanel',

    requires: [
        'Ext.TitleBar',
        'Ext.Img',
        'Ext.Label',
        'Ext.field.Password',
        'Ext.field.Checkbox',
        'Ext.Button'
    ],

    config: {
        cls: 'vertexTheme',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'signInTitleBar',
                title: 'SignIn'
            },
            {
                xtype: 'image',
                centered: false,
                height: 88,
                mode: 'image',
                src: 'resources/images/vertexlogo.jpg'
            },
            {
                xtype: 'label',
                cls: 'vertexThemeText',
                html: 'Please sign in to the system',
                id: 'labelSignInText',
                itemId: 'labelSignInText'
            },
            {
                xtype: 'textfield',
                id: 'loginEmail',
                itemId: 'loginEmail',
                name: 'field',
                required: true,
                placeHolder: 'Email'
            },
            {
                xtype: 'passwordfield',
                id: 'loginPassword',
                itemId: 'loginPassword',
                name: 'loginPassword',
                required: true,
                placeHolder: 'Password'
            },
            {
                xtype: 'checkboxfield',
                id: 'rememberMeBtn',
                itemId: 'rememberMeBtn',
                clearIcon: false,
                label: 'Remember Me',
                labelWidth: '60%',
                name: 'rememberMeBtn',
                value: '1',
                checked: true
            },
            {
                xtype: 'button',
                cls: 'vertexBgText',
                id: 'loginBtn',
                itemId: 'loginBtn',
                text: 'Sign In'
            }
        ]
    }

});