/*
 * File: app/view/mainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vertex.view.mainView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.mainView',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.field.Search',
        'Ext.Panel',
        'Ext.Label',
        'Ext.field.Select'
    ],

    config: {
        cls: 'vertexTheme',
        id: 'mainView',
        itemId: 'mainView',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'mainViewTitle',
                itemId: 'mainViewTitle',
                title: 'SEARCH',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton5',
                        ui: 'plain',
                        text: 'Logout'
                    },
                    {
                        xtype: 'button',
                        align: 'right',
                        ui: 'plain',
                        text: 'History'
                    }
                ]
            },
            {
                xtype: 'searchfield',
                centered: false,
                id: 'companyName',
                itemId: 'companyName',
                name: 'companyName',
                required: true,
                placeHolder: 'Company Name'
            },
            {
                xtype: 'button',
                cls: [
                    'vertexBgText',
                    'vertexBtn'
                ],
                id: 'searchBtn',
                itemId: 'searchBtn',
                text: 'SEARCH'
            },
            {
                xtype: 'button',
                id: 'advanceSearchBtn',
                itemId: 'advanceSearchBtn',
                ui: 'plain',
                text: 'Advance Search'
            },
            {
                xtype: 'panel',
                height: '680px',
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: 'Advance Search',
                        titleAlign: 'left',
                        items: [
                            {
                                xtype: 'label',
                                align: 'right',
                                html: '&#x25BC;'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Country',
                        labelAlign: 'top',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Industry',
                        labelAlign: 'top',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Deal Lead',
                        labelAlign: 'top',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Decision',
                        labelAlign: 'top',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Deal Status',
                        labelAlign: 'top',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Co-Lead',
                        labelAlign: 'top',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Notes',
                        labelAlign: 'top',
                        placeHolder: 'Any Keywords'
                    }
                ]
            }
        ]
    }

});